### ISSUE TITLE
Fields not correctly parsed

### ISSUE THREAD

**Issue by jsteggink** [Appdynamics/elasticsearch-monitoring-extension#5]
Hi,

After trying to add an endpoint for "/_cat/nodes?v", I get an error parsing the fields other than *.percent and name. It wants to parse to "long", but some of them are doubles/floats, like the load_* fields.

It would be nice if there is some way to specify the field type, to override the default.

Best regards,
Jeroen

**Comment by saxenaabhi142** [comment]
Hi Jeroen,

The double/float values will be rounded off to the nearest integer by the extension.

We request you to please raise a support ticket with help@appdynamics.com so that we can investigate further and help you with the issue.
